server:
  port: 8088

web:
  domain: http://127.0.0.1

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 192266
    #&serverTimezone=GMT%2B8
    url: jdbc:mysql://localhost:3306/doubao?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    type: com.zaxxer.hikari.HikariDataSource

logging:
  level:
    root: info
    com.douyuehan.doubao: debug